### ISSUE TITLE
The difference between RORL and RO2O?

### ISSUE THREAD

**Issue by awecefil** [YangRui2015/RORL#2]
Recently, I read both RORL and RO2O paper, and both of them propose almost same way to robust the Q-function and policy by adding OOD loss, policy smooth loss, and Q smooth loss. **Is there some significant difference that I miss between them?**

BTW, if I want to choose one of them to implement in my own project, **which one should I try first?**

**Comment by YangRui2015** [comment]
Hi,

RO2O can be viewed as the application of RORL to the offline-to-online setting, as we have observed that the robustness to state perturbations can mitigate performance instability during policy fine-tuning from offline to online. The method does not contain difference while the setting is different. I suggest you try RORL first, which is the core for both papers.

**Comment by awecefil** [comment]
@YangRui2015 Thank you very much for your quick reply :)
